{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hdf5r.extra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hdf5r.Extra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hdf5r.Extra/hdf5r.Extra_{{ version }}.tar.gz
  sha256: af6385b01efb2a33c37972f245a58d4202b7cc33e2b40b949ec09d642252d7cd

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-checkmate
    - r-dplyr
    - r-easy.utils
    - r-hdf5r >=1.3.8
    - r-rlang
  run:
    - r-base
    - r-matrix
    - r-checkmate
    - r-dplyr
    - r-easy.utils
    - r-hdf5r >=1.3.8
    - r-rlang

test:
  commands:
    - $R -e "library('hdf5r.Extra')"           # [not win]
    - "\"%R%\" -e \"library('hdf5r.Extra')\""  # [win]

about:
  home: https://github.com/ycli1995/hdf5r.Extra
  license: MIT
  summary: Some methods to manipulate 'HDF5' files, extending the 'hdf5r' package. Reading and
    writing R objects to 'HDF5' formats follow the specification of 'AnnData' <https://anndata.readthedocs.io/en/latest/fileformat-prose.html>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
    - conda-forge/r

# Package: hdf5r.Extra
# Type: Package
# Title: Extensions for 'HDF5' R Interfaces
# Version: 0.1.0
# Date: 2024-10-18
# Authors@R: person(given = "Yuchen", family = "Li", email = "ycli1995@outlook.com", role = c("aut", "cre"))
# Description: Some methods to manipulate 'HDF5' files, extending the 'hdf5r' package. Reading and writing R objects to 'HDF5' formats follow the specification of 'AnnData' <https://anndata.readthedocs.io/en/latest/fileformat-prose.html>.
# Depends: R (>= 4.1.0), hdf5r (>= 1.3.8), methods, utils
# Imports: checkmate, dplyr, easy.utils, Matrix, rlang
# License: MIT + file LICENSE
# RoxygenNote: 7.3.1
# Encoding: UTF-8
# URL: https://github.com/ycli1995/hdf5r.Extra
# BugReports: https://github.com/ycli1995/hdf5r.Extra/issues
# Suggests: testthat (>= 3.0.0), withr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-10-18 05:59:35 UTC; mydocker
# Author: Yuchen Li [aut, cre]
# Maintainer: Yuchen Li <ycli1995@outlook.com>
# Repository: CRAN
# Date/Publication: 2024-10-18 06:20:02 UTC
